//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.CollectAssignments = new HashSet<CollectAssignment>();
        }
    
        public int Request_ID { get; set; }
        public int Restaurant_ID { get; set; }
        public System.DateTime Request_DateTime { get; set; }
        public int Maximum_Preservation_Time { get; set; }
        public string FoodItem_Name { get; set; }
        public double FoodItem_Quantity { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectAssignment> CollectAssignments { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
